using AbstractClassExampleProblem;
using ConstructorExampleProblem;
using CopyConstructorProblem;
using PartialClassExampleProblem;
using PrivateConstructorProblem;
using SealedClassProblem;
using StaticClassProblem;
using StaticConstructorProblem;
using AccessModifierExample;
using PrivateMemberAccessModifiers;
using ProtectedExampleAccessModifiers;
using InternalClassExampleAccessModifiers;
using PrivateProtectedExampleProblem;
using FieldTypesProblem;

//AbstractProgram.Solution();
//new PartialClassExample().Solution();
//MainClass.Solution();
//StaticClass.Solution();
//ConstructorExampleProblem.MainClass.Solution();
//StaticConstructorMain.Solution();
//MainPrivateConstructor.Solution();
//MainCopyConstructor.Solution();
//MainPublicClass.Solution();
//MainPrivateMethod.Solution();
//ProtectedExampleMain.Solution();
//MainInternalClass.Solution();
//PrivateProtectedProgram.MainMethod();
MainProgramFieldTypes.Solution();